import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import {
  chmod,
  mkdtemp,
  mkdir,
  readFile,
  readlink,
  rm,
  symlink,
  writeFile,
} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { runSetup } from '../lib/setup.js';
import { GENERATED_MARKER } from '../lib/codex-config-sync.js';

describe('lib/setup', () => {
  it('should repair the inspected configuration target without invoking Stow', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const codex = path.join(home, '.codex');
    const output = path.join(codex, 'config.toml');
    const local = path.join(codex, 'config.local.toml');
    const environment = {
      PATH: '/nonexistent-setup-bin',
      TANAAB_CODEX_CONFIG_SHARED: '',
      TANAAB_CODEX_CONFIG_LOCAL: '',
      TANAAB_CODEX_CONFIG_OUTPUT: '',
      TANAAB_CODEX_CONFIG_SYNC: 'false',
      TANAAB_STOW_TARGET: '/nonexistent-setup-home',
    };
    const original = Object.fromEntries(
      Object.keys(environment).map((key) => [key, process.env[key]]),
    );
    await mkdir(codex);
    await mkdir(path.join(root, '.agent-system'));
    await writeFile(
      path.join(root, '.agent-system', 'agent.yaml'),
      JSON.stringify({
        'schema-version': 1,
        models: { default: { model: 'openai/fixture-model', effort: 'high' } },
      }),
    );
    await writeFile(path.join(codex, 'config.shared.toml'), 'personality = "pragmatic"\n');
    await writeFile(local, 'custom_setting = "preserved"\n');
    await writeFile(
      output,
      '# Generated by @pirog/me aisync.\nmodel = "old"\n[plugins."fixture@store"]\nenabled = true\n',
    );
    Object.assign(process.env, environment);
    try {
      assert.equal(await runSetup(['check', 'config'], { root, home }), 1);
      assert.equal(await runSetup(['apply', 'config'], { root, home }), 0);
      assert.equal(await runSetup(['check', 'config'], { root, home }), 0);
      const content = await readFile(output, 'utf8');
      const config = globalThis.Bun.TOML.parse(content);
      assert.equal(config.model, 'fixture-model');
      assert.equal(config.custom_setting, 'preserved');
      assert.deepEqual(config.plugins['fixture@store'], { enabled: true });
      assert.ok(content.startsWith(`# ${GENERATED_MARKER}`));
      assert.equal(await readFile(local, 'utf8'), 'custom_setting = "preserved"\n');
    } finally {
      for (const [key, value] of Object.entries(original)) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
      await rm(root, { recursive: true });
      await rm(home, { recursive: true });
    }
  });

  it('should detect Brewfile and Bun pin drift without changing packages', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const bin = path.join(home, 'bin');
    const bunPrefix = path.join(home, 'bun-formula');
    const nodePrefix = path.join(home, 'node-formula');
    await mkdir(bin);
    await mkdir(path.join(bunPrefix, 'bin'), { recursive: true });
    await mkdir(path.join(nodePrefix, 'bin'), { recursive: true });
    await writeFile(path.join(bunPrefix, 'bin', 'bun'), '#!/bin/sh\necho 9.8.7\n');
    await chmod(path.join(bunPrefix, 'bin', 'bun'), 0o755);
    await writeFile(path.join(nodePrefix, 'bin', 'node'), '#!/bin/sh\necho v26.1.0\n');
    await chmod(path.join(nodePrefix, 'bin', 'node'), 0o755);
    await writeFile(path.join(root, 'Brewfile'), 'brew "stow"\n');
    await writeFile(path.join(root, '.bun-version'), '9.8.7\n');
    const brew = path.join(bin, 'brew');
    for (const command of ['curl', 'git', 'stow', 'zsh']) {
      const executable = path.join(bin, command);
      await writeFile(executable, '#!/bin/sh\nexit 0\n');
      await chmod(executable, 0o755);
    }
    await writeFile(
      brew,
      `#!/bin/sh
if [ "$1" = list ]; then exit 1; fi
if [ "$1" = bundle ]; then
  if [ "$2" = check ]; then
    [ "$HOMEBREW_NO_AUTO_UPDATE" = 1 ] || exit 1
  else
    [ "$HOMEBREW_NO_AUTO_UPDATE" = 0 ] || exit 2
  fi
  exit 0
fi
if [ "$2" = oven-sh/bun/bun ]; then echo '${bunPrefix}'; exit 0; fi
if [ "$2" = node@26 ]; then echo '${nodePrefix}'; exit 0; fi
exit 2
`,
    );
    await chmod(brew, 0o755);

    const originalPath = process.env.PATH;
    const originalAutoUpdate = process.env.HOMEBREW_NO_AUTO_UPDATE;
    process.env.PATH = `${bin}:${originalPath}`;
    process.env.HOMEBREW_NO_AUTO_UPDATE = '0';
    try {
      assert.equal(await runSetup(['check', 'brewfile'], { root, home }), 0);
      assert.equal(await runSetup(['apply', 'brewfile'], { root, home }), 0);
      await writeFile(path.join(root, '.bun-version'), '0.0.0\n');
      assert.equal(await runSetup(['check', 'brewfile'], { root, home }), 1);
    } finally {
      process.env.PATH = originalPath;
      if (originalAutoUpdate === undefined) delete process.env.HOMEBREW_NO_AUTO_UPDATE;
      else process.env.HOMEBREW_NO_AUTO_UPDATE = originalAutoUpdate;
    }
  });

  it('should distinguish an unchanged Stow simulation from pending links', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const bin = path.join(home, 'bin');
    const stow = path.join(bin, 'stow');
    await mkdir(bin);
    const sourceCodex = path.join(root, 'dotfiles', 'ai', '.codex');
    const homeCodex = path.join(home, '.codex');
    const log = path.join(home, 'stow-args');
    await mkdir(path.join(sourceCodex, 'plugins'), { recursive: true });
    await mkdir(path.join(homeCodex, 'plugins'), { recursive: true });
    await writeFile(
      stow,
      `#!/bin/sh\nprintf '%s\\n' "$@" > '${log}'\necho "WARNING: in simulation mode so not modifying filesystem."\n`,
    );
    await chmod(stow, 0o755);
    const originalPath = process.env.PATH;
    process.env.PATH = `${bin}:${originalPath}`;
    try {
      assert.equal(await runSetup(['check', 'dotfiles'], { root, home }), 0);
      const inspected = (await readFile(log, 'utf8')).split('\n');
      assert.ok(inspected.includes('--simulate'));
      assert.ok(inspected.includes('--restow'));
      assert.ok(inspected.includes('--no-folding'));
      await rm(homeCodex, { recursive: true });
      await symlink(sourceCodex, homeCodex);
      assert.equal(await runSetup(['check', 'dotfiles'], { root, home }), 1);
      assert.equal(await runSetup(['apply', 'dotfiles'], { root, home }), 2);
      assert.equal(await readlink(homeCodex), sourceCodex);
      await rm(homeCodex);
      await mkdir(homeCodex);
      await symlink(path.join(sourceCodex, 'plugins'), path.join(homeCodex, 'plugins'));
      assert.equal(await runSetup(['check', 'dotfiles'], { root, home }), 1);
      await rm(path.join(homeCodex, 'plugins'));
      await mkdir(path.join(homeCodex, 'plugins'));
      await writeFile(stow, '#!/bin/sh\necho "LINK: .codex/config.shared.toml"\n');
      assert.equal(await runSetup(['check', 'dotfiles'], { root, home }), 1);
      await writeFile(stow, `#!/bin/sh\nprintf '%s\\n' "$@" > '${log}'\n`);
      assert.equal(await runSetup(['apply', 'dotfiles'], { root, home }), 0);
      assert.match(await readFile(log, 'utf8'), /--restow/);
      assert.match(await readFile(log, 'utf8'), /--no-folding/);
    } finally {
      process.env.PATH = originalPath;
    }
  });

  it('should skip a declared optional source plugin only when no checkout or link exists', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const args = ['check', 'plugin', 'canon', 'tanaab', 'optional'];

    assert.equal(await runSetup(args, { root, home }), 0);
    await mkdir(path.join(root, 'dotfiles', 'ai', '.codex', 'plugins'), { recursive: true });
    await symlink(
      'missing-source',
      path.join(root, 'dotfiles', 'ai', '.codex', 'plugins', 'tanaab'),
    );
    assert.equal(await runSetup(args, { root, home }), 2);
  });

  it('should reject malformed step declarations before any work', async () => {
    assert.equal(await runSetup(['check', 'plugin', '../canon', 'tanaab']), 2);
    assert.equal(await runSetup(['check', 'dotfiles', 'unexpected']), 2);
    assert.equal(await runSetup(['repair', 'dotfiles']), 2);
  });

  it('should check local plugin installation and cache drift', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const source = path.join(home, 'tanaab', 'canon');
    const links = path.join(root, 'dotfiles', 'ai', '.codex', 'plugins');
    const cli = path.join(root, 'node_modules', '.bin', 'codex-tools');
    await mkdir(path.dirname(cli), { recursive: true });
    await mkdir(links, { recursive: true });
    execFileSync('git', ['init', '-q', source]);
    execFileSync('git', [
      '-C',
      source,
      'remote',
      'add',
      'origin',
      'git@github.com:tanaabased/canon.git',
    ]);
    await symlink(path.relative(links, source), path.join(links, 'tanaab'));
    await writeFile(
      cli,
      '#!/bin/sh\nif [ "$1" = status ]; then echo \'{"ok":true,"inspection":{"installed":true,"enabled":true}}\'; exit 0; fi\nexit 0\n',
    );
    await chmod(cli, 0o755);
    const args = ['check', 'plugin', 'canon', 'tanaab', 'optional'];
    assert.equal(await runSetup(args, { root, home }), 0);

    await writeFile(
      cli,
      '#!/bin/sh\nif [ "$1" = status ]; then echo \'{"ok":true,"inspection":{"installed":true,"enabled":true}}\'; exit 0; fi\nexit 1\n',
    );
    assert.equal(await runSetup(args, { root, home }), 1);

    await writeFile(
      cli,
      '#!/bin/sh\necho \'{"ok":false,"inspection":{"installed":false,"enabled":false}}\'\nexit 1\n',
    );
    assert.equal(await runSetup(args, { root, home }), 0);
  });

  it('should sync an installed source plugin cache on apply', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const links = path.join(root, 'dotfiles', 'ai', '.codex', 'plugins');
    const cli = path.join(root, 'node_modules', '.bin', 'codex-tools');
    const bin = path.join(home, 'bin');
    const log = path.join(home, 'codex-tools-args');
    await mkdir(links, { recursive: true });
    await mkdir(path.dirname(cli), { recursive: true });
    await mkdir(bin);
    await symlink(path.relative(links, root), path.join(links, 'piroplugin'));
    await writeFile(path.join(bin, 'bun'), '#!/bin/sh\nexit 0\n');
    await chmod(path.join(bin, 'bun'), 0o755);
    await writeFile(
      cli,
      `#!/bin/sh\nif [ "$1" = status ]; then echo '{"ok":true,"inspection":{"installed":true,"enabled":true}}'; exit 0; fi\nprintf '%s\\n' "$@" > '${log}'\n`,
    );
    await chmod(cli, 0o755);
    const originalPath = process.env.PATH;
    process.env.PATH = `${bin}:${originalPath}`;
    try {
      assert.equal(await runSetup(['apply', 'plugin', 'me', 'piroplugin'], { root, home }), 0);
      assert.match(await readFile(log, 'utf8'), /^cache\nsync\n/);
    } finally {
      process.env.PATH = originalPath;
    }
  });

  it('should restow only AI links into the supplied home when creating a plugin link', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const bin = path.join(home, 'bin');
    const cli = path.join(root, 'node_modules', '.bin', 'codex-tools');
    const log = path.join(home, 'stow-args');
    await mkdir(bin);
    await mkdir(path.dirname(cli), { recursive: true });
    await writeFile(path.join(bin, 'bun'), '#!/bin/sh\nexit 0\n');
    await chmod(path.join(bin, 'bun'), 0o755);
    await writeFile(path.join(bin, 'stow'), `#!/bin/sh\nprintf '%s\\n' "$@" > '${log}'\n`);
    await chmod(path.join(bin, 'stow'), 0o755);
    await writeFile(
      cli,
      '#!/bin/sh\nif [ "$1" = status ]; then echo \'{"inspection":{"installed":true,"enabled":true}}\'; fi\n',
    );
    await chmod(cli, 0o755);
    const originalPath = process.env.PATH;
    process.env.PATH = `${bin}:${originalPath}`;
    try {
      assert.equal(await runSetup(['apply', 'plugin', 'me', 'piroplugin'], { root, home }), 0);
      const args = (await readFile(log, 'utf8')).trim().split('\n');
      assert.equal(args[args.indexOf('--target') + 1], home);
      assert.equal(args.at(-1), 'ai');
      assert.ok(args.includes('--restow'));
      assert.ok(args.includes('--no-folding'));
      const link = path.join(root, 'dotfiles', 'ai', '.codex', 'plugins', 'piroplugin');
      assert.equal(path.resolve(path.dirname(link), await readlink(link)), root);
      await assert.rejects(readFile(path.join(home, '.codex', 'config.toml')), { code: 'ENOENT' });
    } finally {
      process.env.PATH = originalPath;
      await rm(root, { recursive: true });
      await rm(home, { recursive: true });
    }
  });

  it('should emit bounded safe operation diagnostics only in runner debug mode', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const links = path.join(root, 'dotfiles', 'ai', '.codex', 'plugins');
    const cli = path.join(root, 'node_modules', '.bin', 'codex-tools');
    const bin = path.join(home, 'bin');
    await mkdir(links, { recursive: true });
    await mkdir(path.dirname(cli), { recursive: true });
    await mkdir(bin);
    await symlink(path.relative(links, root), path.join(links, 'piroplugin'));
    await writeFile(path.join(bin, 'bun'), '#!/bin/sh\nexit 0\n');
    await chmod(path.join(bin, 'bun'), 0o755);
    await writeFile(
      cli,
      `#!/bin/sh\nif [ "$1" = status ]; then echo '{"ok":true,"inspection":{"installed":true,"enabled":true}}'; exit 0; fi\necho 'permission denied token=super-secret' >&2\necho '${'x'.repeat(20000)}' >&2\nexit 1\n`,
    );
    await chmod(cli, 0o755);
    const originalPath = process.env.PATH;
    const originalDebug = process.env.RUNNER_DEBUG;
    let stderr = '';
    const originalWrite = process.stderr.write;
    process.stderr.write = (chunk) => {
      stderr += chunk;
      return true;
    };
    process.env.PATH = `${bin}:${originalPath}`;
    try {
      delete process.env.RUNNER_DEBUG;
      assert.equal(await runSetup(['apply', 'plugin', 'me', 'piroplugin'], { root, home }), 2);
      assert.doesNotMatch(stderr, /debug: setup operation=/);
      assert.match(stderr, /^plugin: .* failed \(1\)\.$/m);
      stderr = '';
      process.env.RUNNER_DEBUG = '1';
      assert.equal(await runSetup(['apply', 'plugin', 'me', 'piroplugin'], { root, home }), 2);
      assert.match(stderr, /debug: setup operation=plugin\.cache-sync reason=access was denied/);
      assert.doesNotMatch(stderr, /super-secret|permission denied|x{100}/);
      assert.ok(Buffer.byteLength(stderr) < 500);
    } finally {
      process.stderr.write = originalWrite;
      process.env.PATH = originalPath;
      if (originalDebug === undefined) delete process.env.RUNNER_DEBUG;
      else process.env.RUNNER_DEBUG = originalDebug;
    }
  });

  it('should sync a newly installed source plugin before reporting healthy', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'me-setup-root-'));
    const home = await mkdtemp(path.join(os.tmpdir(), 'me-setup-home-'));
    const links = path.join(root, 'dotfiles', 'ai', '.codex', 'plugins');
    const cli = path.join(root, 'node_modules', '.bin', 'codex-tools');
    const bin = path.join(home, 'bin');
    const log = path.join(home, 'codex-tools-args');
    const installed = path.join(home, 'installed');
    const synced = path.join(home, 'synced');
    await mkdir(links, { recursive: true });
    await mkdir(path.dirname(cli), { recursive: true });
    await mkdir(bin);
    await symlink(path.relative(links, root), path.join(links, 'piroplugin'));
    await writeFile(path.join(bin, 'bun'), '#!/bin/sh\nexit 0\n');
    await chmod(path.join(bin, 'bun'), 0o755);
    await writeFile(
      cli,
      `#!/bin/sh
if [ "$1" = status ]; then
  if [ -e '${installed}' ]; then
    echo '{"ok":true,"inspection":{"installed":true,"enabled":true}}'
    exit 0
  fi
  echo '{"ok":false,"inspection":{"installed":false,"enabled":false}}'
  exit 1
fi
if [ "$1" = install ]; then
  echo install >> '${log}'
  touch '${installed}'
  exit 0
fi
if [ "$1" = cache ] && [ "$2" = sync ]; then
  echo sync >> '${log}'
  touch '${synced}'
  exit 0
fi
if [ "$1" = cache ] && [ "$2" = check ]; then
  test -e '${synced}'
  exit $?
fi
exit 2
`,
    );
    await chmod(cli, 0o755);
    const originalPath = process.env.PATH;
    process.env.PATH = `${bin}:${originalPath}`;
    try {
      const args = ['plugin', 'me', 'piroplugin'];
      assert.equal(await runSetup(['check', ...args], { root, home }), 1);
      assert.equal(await runSetup(['apply', ...args], { root, home }), 0);
      assert.equal(await readFile(log, 'utf8'), 'install\nsync\n');
      assert.equal(await runSetup(['check', ...args], { root, home }), 0);
    } finally {
      process.env.PATH = originalPath;
    }
  });
});
