tap "oven-sh/bun", trusted: true

cask "1password"
cask "1password-cli@beta"
cask "codex"
cask "codex-app"
cask "google-chrome"
cask "openclaw"
cask "tailscale-app"
cask "visual-studio-code"
cask "warp"

brew "curl"
brew "gh"
brew "git"
brew "imagemagick"
brew "jq"
brew "node@24"
brew "python@3.14"
brew "stow"
brew "zsh"
brew "oven-sh/bun/bun"
